"""Created the 'list' and 'list_item' tables

Revision ID: 37365b772e1c
Revises: 
Create Date: 2023-03-10 20:11:51.595898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37365b772e1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('list_id', sa.Integer(), nullable=True),
        sa.Column('body', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_item')
    op.drop_table('list')
    # ### end Alembic commands ###
